linters-settings:
  govet:
    check-shadowing: true
  maligned:
    suggest-new: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gci:
    sections:
      - standard # Captures all standard packages if they do not match another section.
      - prefix(github.com/maxgio92/krawler) # Groups all imports with the specified Prefix.
      - default # Contains all imports that could not be matched to another section type.
  tagliatelle:
    case:
      rules:
        json: snake

linters:
  enable-all: true
  disable:
    - interfacer
    - godox
    - golint
    - scopelint
    - maligned
    - gochecknoglobals
    - gochecknoinits
    - exhaustivestruct
    - exhaustruct
    - ireturn
    - lll
    - nonamedreturns
    - wrapcheck
    - varnamelen

issues:
  exclude-rules:
  - path: /
    linters:
    - typecheck

run:
  skip-dirs:
    - pkg/utils/matrix
    - pkg/utils/template
