distros:
  centos:

    archs:
    - "x86_64"
    - "aarch64"

    mirrors:
    - url: https://archive.kernel.org/centos-vault
      name: Archive
    - url: https://mirrors.edge.kernel.org/centos
      name: Edge

    repositories:
    - name: old
      uri: "/{{ .old_repos }}/{{ .archs }}/{{ .packages_folder }}/"
    - name: new
      uri: "/{{ .new_repos }}/{{ .archs }}/os/{{ .packages_folder }}/"

    vars:
      new_repos:
      - "BaseOS"
      - "AppStream"
      old_repos:
      - "os"
      - "updates"
      packages_folder:
      - "Packages"