distros:
  centos:
    vars:
      new_repos:
      - "BaseOS"
      - "AppStream"

      old_repos:
      - "os"
      - "updates"

      packages_folder:
      - "Packages"

    versions:
    - "7"
    - "8"

    archs:
    - "x86_64"
    - "aarch64"

    mirrors:
    - url: https://archive.kernel.org/centos-vault
    - url: https://mirrors.edge.kernel.org/centos

    repositories:
    - name: old
      uri: "/{{ .old_repos }}/{{ .archs }}/{{ .packages_folder }}/"
    - name: new
      uri: "/{{ .new_repos }}/{{ .archs }}/os/{{ .packages_folder }}/"
